flutter_native_splash:
  #color: "#42a5f5"
  background_image: "assets/Splash.png"
  android_12:
  android: true
  ios: false
  web: false

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21